---
title: "NLS eReader Braille Display"
format: html
---

## Purpose of this Page
Some of the studies we conduct here at the (x)Ability Design Lab have an eligibility criterion requiring perspective participants to have access to a refreshable braille display. While companies like [Orbit Research](https://www.orbitresearch.com/) offer these devices at a relatively lower cost when compared with what's on the market, we understand that a no-cost solution may be more ideal depending on an individual's current situation. This is why we have put together this guide to walk you through the process to request and receive a refreshable braille display from the [National Library Service for the Blind and Print Disabled](https://www.loc.gov/nls/) (NLS). 

Some important things to note:
* You must be an NLS patron.
* Availability of the refreshable braille display eReaders from the NLS is not guaranteed.
* While there is no cost associated, patrons are loaning these eReaders from the NLS for an unspecified period of time.

## How to Request an NLS Refreshable Braille Display (eReader)
1. If you are not one already, enroll to [become an NLS patron](https://www.loc.gov/nls/how-to-enroll/). Be sure to refer to the eligibility criteria and steps outlined on that page before you apply.
2. Once you are enrolled by the NLS as a patron and have access to their services, find your [network library's contact information from this page](https://www.loc.gov/nls/find-your-library/). 
3. Once you have identified your regional library, give them a call and ask them if you can request an NLS refreshable braille display eReader to read books from BARD.
4. If they are still accepting requests for these eReaders, they'll take down your name, mailing address, and any other relevant information. Please ensure that you provide them with a mailing address that you feel comfortable having the braille display sent to.
5. It will take anywhere between 1 to 4 weeks for them to process your request and mail you the loaner eReader. This estimate may have changed since we went through the process in Q2 of 2024.
6. Once you receive the device, feel free to reference the enclosed materials like the User Guide. You'll want to connect the device to your computer to meet our eligibility criterion for some of our ongoing studies.

For more information about this process, or to learn about available NLS equipment and other device recommendations from the NLSk, check out this [Equipment for NLS Materials page](https://www.loc.gov/nls/services-and-resources/equipment-for-nls-materials/).

If you have any questions or concerns, please email [xability-lab@illinois.edu](mailto:xability-lab@illinois.edu), and include *NLS*, all caps in the subject line.

We thank you for your expressed interest in our research and look forward to your participation in our ongoing studies.

*This guide was last updated on September 24, 2024 at 9 PM CDT*